"$schema" = 'https://starship.rs/config-schema.json'

format = """
[░▒▓](color_f1)\
$os\
[](fg:color_f1 bg:color_f2)\
$username\
[](fg:color_f2 bg:color_f3)\
$hostname\
[](fg:color_f3 bg:color_f4)\
$directory\
[](fg:color_f4 bg:color_f5)\
$git_branch\
$git_status\
[](fg:color_f5 bg:color_f6)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_f6 bg:color_f7)\
$docker_context\
$conda\
[](fg:color_f7 bg:color_f8)\
$time\
[](fg:color_f8)\
$line_break$character"""


palette = 'field_color'

[palettes.field_color]
color_f1 = '#b6b61f'
color_f2 = '#3c3836'
color_f3 = '#665c54'
color_f4 = '#98971a'
color_f5 = '#606010'
color_f6 = '#44440c'
color_f7 = '#282807'
color_f8 = '#1d2021'
color_fg0 = '#fbf1c7'
color_red = '#cc241d'
color_green = '#98971a'
color_purple = '#b16286'
color_yellow = '#d79921'
color_blue = '#458588'
color_aqua = '#689d6a'
color_orange = '#d65d0e'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'

[os]
disabled = false
style = "bg:color_f1 fg:color_bg1"
format = '[ $symbol ]($style)'

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:color_f2 fg:color_fg0"
style_root = "bg:color_f2 fg:color_fg0"
format = '[ $user ]($style)'

[hostname]
ssh_only = false
style = "bg:color_f3 fg:color_fg0"
format = '[ $ssh_symbol](bold bg:color_f3 fg:color_blue)[$hostname ](bold $style)'
trim_at = '.companyname.com'
disabled = false

[directory]
style = "bg:color_f4 fg:color_fg0"
format = "[ $path ]($style)"
truncation_length = 5
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_f5"
format = '[[ $symbol $branch ](fg:color_fg0 bg:color_f5)]($style)'

[git_status]
style = "fg:color_red bg:color_f5"
format = '[($all_status$ahead_behind)](fg:color_fg0 bg:color_red)'

[nodejs]
symbol = ""
style = "bg:color_f6"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_f6)]($style)'

[c]
symbol = " "
style = "bg:color_f6"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_f6)]($style)'

[rust]
symbol = ""
style = "bg:color_f6"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_f6)]($style)'

[golang]
symbol = ""
style = "bg:color_f6"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_f6)]($style)'

[php]
symbol = ""
style = "bg:color_f6"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_f6)]($style)'

[java]
symbol = " "
style = "bg:color_f6"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_f6)]($style)'

[kotlin]
symbol = ""
style = "bg:color_f6"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_f6)]($style)'

[haskell]
symbol = ""
style = "bg:color_f6"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_f6)]($style)'

[python]
symbol = ""
style = "bg:color_f6"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_f6)]($style)'

[docker_context]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_f7)]($style)'

[conda]
style = "bg:color_bg3"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:color_f7)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_f8"
format = '[[  $time ](fg:color_fg0 bg:color_f8)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[ 󰘧](bold fg:color_green)'
error_symbol = '[ 󰘧](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
